[package]
name = "handybars"
version = "0.1.1"
edition = "2021"
license = "MIT"
authors = ["0x00002a"]
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
proptest = "1.0.0"
